version: "3"
services:
  db:
    image: e1d66a2a0aa1
    container_name: hyunsa-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: taskDB
      MYSQL_ROOT_PASSWORD: "whalsdn1!"
      MYSQL_ROOT_HOST: '%'
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - "/home/minwoo/DBMS/data:/var/lib/mysql"
      - "/home/minwoo/DBMS/log:/var/log/mysql"
      - "/home/minwoo/DBMS/conf/my.cnf:/etc/mysql/conf.d/my.cnf"
        
